apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laxmansmr-us/argoflow
    targetRevision: master
    chart: jaeger-operator
    helm:
      parameters:
        - name: image.repository
          value: jaegertracing/jaeger-operator
        - name: image.tag
          value: 1.22.0
        - name: jaeger.create
          value: "true"
        - name: jaeger.namespace
          value: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
