apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-feature-discovery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laxmansmr-us/argoflow
    targetRevision: master
    chart: gpu-feature-discovery
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
