apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "4x9BQd2E9G0lMJJsZjaLh5WSNr5dt2agrp66ZrdCrMQgytxUb+ySqpAOaIHOioYi\nz3AZCNBLcEReWZebPxVQ0AnolpWSZ6Ra9/qkbzdpHi307gZBpGqwzUM9Xsy1kdIO\nHeE6ehpwchxvyVrWBjlImJDp8iOtq3nqF7nr2nK4ipY="
